# example 

> example of using streamlit in a jupyter notebook

[![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://ddobrinskiy-jupyter.streamlit.app/)


In this examle we use [nbdev](https://nbdev.fast.ai/) to export only the relevant cells of our notebook to `.py` file

- start the cells you want exported with the `#|export` or `#|exporti` directive

- run `nb_export` to convert the `.ipynb` to `.py`

```python
from nbdev.export import nb_export
nb_export('99_example.ipynb', lib_path='.', name='example')
```

Alternatively you can use native `nbconvert` from bash, but nbdev is superior :)

In [1]:
%load_ext autoreload

%autoreload 2

In [9]:
!pip install streamlit_jupyter

Requirement already satisfied: streamlit_jupyter in /opt/conda/lib/python3.11/site-packages (0.2.1)
Requirement already satisfied: fastcore in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (1.7.20)
Requirement already satisfied: ipywidgets==7.7.2 in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (7.7.2)
Requirement already satisfied: jupyter in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (1.1.1)
Requirement already satisfied: stqdm in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (0.0.5)
Requirement already satisfied: streamlit>=1.19 in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (1.43.2)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (0.9.0)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from streamlit_jupyter) (4.67.1)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.11/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (6.29.5)
Requirement already satisfied: ipython-genutils~=0.2.0 in /opt/conda/lib/python3.11/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/conda/lib/python3.11/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (5.14.3)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /opt/conda/lib/python3.11/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /opt/conda/lib/python3.11/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (8.29.0)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in /opt/conda/lib/python3.11/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (1.1.11)
Requirement already satisfied: altair<6,>=4.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (5.4.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (8.1.7)
Requirement already satisfied: numpy<3,>=1.23 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (17.0.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (8.5.0)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/conda/lib/python3.11/site-packages (from streamlit>=1.19->streamlit_jupyter) (6.4.2)
Requirement already satisfied: notebook in /opt/conda/lib/python3.11/site-packages (from jupyter->streamlit_jupyter) (7.2.2)
Requirement already satisfied: jupyter-console in /opt/conda/lib/python3.11/site-packages (from jupyter->streamlit_jupyter) (6.6.3)
Requirement already satisfied: nbconvert in /opt/conda/lib/python3.11/site-packages (from jupyter->streamlit_jupyter) (7.16.4)
Requirement already satisfied: jupyterlab in /opt/conda/lib/python3.11/site-packages (from jupyter->streamlit_jupyter) (4.2.6)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/conda/lib/python3.11/site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (4.23.0)
Requirement already satisfied: narwhals>=1.5.2 in /opt/conda/lib/python3.11/site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.11/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.19->streamlit_jupyter) (4.0.11)
Requirement already satisfied: comm>=0.1.1 in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (1.8.10)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.1.7)
Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (1.6.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (5.9.8)
Requirement already satisfied: pyzmq>=24 in /opt/conda/lib/python3.11/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (26.2.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.19.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.18.0)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.6.3)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (4.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (2023.3)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (2024.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (2024.8.30)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /opt/conda/lib/python3.11/site-packages (from notebook->jupyter->streamlit_jupyter) (2.14.2)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /opt/conda/lib/python3.11/site-packages (from notebook->jupyter->streamlit_jupyter) (2.27.3)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in /opt/conda/lib/python3.11/site-packages (from notebook->jupyter->streamlit_jupyter) (0.2.4)
Requirement already satisfied: async-lru>=1.0.0 in /opt/conda/lib/python3.11/site-packages (from jupyterlab->jupyter->streamlit_jupyter) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in /opt/conda/lib/python3.11/site-packages (from jupyterlab->jupyter->streamlit_jupyter) (0.28.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from jupyterlab->jupyter->streamlit_jupyter) (2.2.5)
Requirement already satisfied: setuptools>=40.1.0 in /opt/conda/lib/python3.11/site-packages (from jupyterlab->jupyter->streamlit_jupyter) (75.6.0)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (6.2.0)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.10.1)
Requirement already satisfied: nbformat>=5.7 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (1.5.0)
Requirement already satisfied: tinycss2 in /opt/conda/lib/python3.11/site-packages (from nbconvert->jupyter->streamlit_jupyter) (1.4.0)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.11/site-packages (from bleach!=5.0.0->nbconvert->jupyter->streamlit_jupyter) (0.5.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.19->streamlit_jupyter) (5.0.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.11/site-packages (from httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (4.7.0)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.11/site-packages (from httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/conda/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (0.14.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/conda/lib/python3.11/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.22.3)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (4.3.6)
Requirement already satisfied: argon2-cffi>=21.1 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (23.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.5.3)
Requirement already satisfied: overrides>=5.0 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.21.1)
Requirement already satisfied: send2trash>=1.8.2 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /opt/conda/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in /opt/conda/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter->streamlit_jupyter) (2.16.0)
Requirement already satisfied: json5>=0.9.0 in /opt/conda/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter->streamlit_jupyter) (0.10.0)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/conda/lib/python3.11/site-packages (from nbformat>=5.7->nbconvert->jupyter->streamlit_jupyter) (2.21.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.11/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.13)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.11/site-packages (from beautifulsoup4->nbconvert->jupyter->streamlit_jupyter) (2.5)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (3.0.0)
Requirement already satisfied: pure_eval in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.3)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.11/site-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in /opt/conda/lib/python3.11/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (21.2.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /opt/conda/lib/python3.11/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in /opt/conda/lib/python3.11/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in /opt/conda/lib/python3.11/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /opt/conda/lib/python3.11/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.1.1)
Requirement already satisfied: fqdn in /opt/conda/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.5.1)
Requirement already satisfied: isoduration in /opt/conda/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /opt/conda/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (3.0.0)
Requirement already satisfied: uri-template in /opt/conda/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /opt/conda/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (24.11.1)
Requirement already satisfied: cffi>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.17.1)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.22)
Requirement already satisfied: arrow>=0.15.0 in /opt/conda/lib/python3.11/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /opt/conda/lib/python3.11/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.9.0.20241206)

In [14]:
!pip install --upgrade streamlit

ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade

In [10]:
# |exporti

from datetime import datetime

import streamlit as st

import streamlit as st

from streamlit_jupyter import StreamlitPatcher, tqdm

In [11]:
sp = StreamlitPatcher()
sp.jupyter()  # register patcher with streamlit

AttributeError: module 'streamlit' has no attribute 'experimental_data_editor'

In [5]:
# |exporti

st.title("Example")

# Example

In [6]:
# |exporti

st.markdown(
    """

This is a test page demonstrating the use of `streamlit_jupyter`.

If you're seeing this in jupyter, then it's working!

"""
)

This is a test page demonstrating the use of `streamlit_jupyter`.

If you're seeing this in jupyter, then it's working!

In [7]:
sp.registered_methods

{'caption', 'dataframe', 'header', 'markdown', 'subheader', 'title', 'write'}

In [8]:
# |exporti

name = st.text_input("What's your name?", "John")

2025-03-17 09:50:36.520 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 09:50:36.521 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 09:50:36.523 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 09:50:36.524 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 09:50:36.526 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2025-03-17 09:50:36.527 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 09:50:36.602
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-03-17 09:50:36.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [8]:
# |exporti

date = st.date_input("Choose a date", datetime.now().date())

DatePicker(value=Timestamp('2024-07-09 00:00:00'), description='Choose a date')

In [9]:
# |exporti

st.markdown(f"## Hello {name}!\n## The date is {date.strftime('%Y-%m-%d')}")

## Hello John!
## The date is 2024-07-09

In [10]:
# |exporti

import time

import pandas as pd

st.subheader("A cached dataframe")


@st.cache_data()
def get_data(date):
    for i in tqdm(range(10)):
        time.sleep(0.1)
    return pd.DataFrame(
        {"date": pd.date_range(date, periods=3), "c": [7, 8, 5], "d": [10, 11, 7]}
    ).set_index("date")


df = get_data(date)
st.write(df)

### A cached dataframe

  0%|          | 0/10 [00:00<?, ?it/s]

            c   d
date
2024-07-09  7  10
2024-07-10  8  11
2024-07-11  5   7

In [11]:
# |exporti

st.subheader("Data Editor")
df = pd.DataFrame(
    [
        {
            "command": "st.selectbox",
            "rating": 4,
            "is_widget": True,
        },
        {
            "command": "st.balloons",
            "rating": 5,
            "is_widget": False,
        },
        {
            "command": "st.time_input",
            "rating": 3,
            "is_widget": True,
        },
    ]
)
edited_df = st.data_editor(df)

### Data Editor

         command  rating  is_widget
0   st.selectbox       4       True
1    st.balloons       5      False
2  st.time_input       3       True

In [12]:
# |exporti


st.subheader("One more cache example")


@st.cache_resource(ttl=3600)
def get_resource():
    st.write("Getting resource...")
    for i in tqdm(range(5)):
        time.sleep(0.1)
    return {
        "foo": "bar",
        "baz": [1, 2, 3],
        "qux": {"a": 1, "b": 2, "c": 3},
    }


records = get_resource()
st.json(records)

### One more cache example

Getting resource...

  0%|          | 0/5 [00:00<?, ?it/s]

```json
{
  "foo": "bar",
  "baz": [
    1,
    2,
    3
  ],
  "qux": {
    "a": 1,
    "b": 2,
    "c": 3
  }
}
```

In [13]:
# |exporti

st.subheader("Ploting")

import plotly.express as px

df_daily = df[["rating"]].mean(axis="columns").rename("daily_average")
fig = px.line(df_daily, title="Daily mean", width=600)
st.write(fig)

### Ploting

In [14]:
# | exporti

st.metric("Speed", 300, 210, delta_color="normal", label_visibility="visible")

`delta_color` argument is not supported in Jupyter notebooks, but will be applied in Streamlit
`label_visibility` argument is not supported in Jupyter notebooks, but will be applied in Streamlit

In [15]:
# | exporti

st.metric("Speed", 300, 210)

In [16]:
# |exporti

st.code("print(1+1)", language="python")

```python
print(1+1)
```

In [17]:
# |exporti

show_code = st.checkbox("Show code", value=True)

Checkbox(value=True, description='Show code', indent=False)

In [18]:
# |exporti

if show_code:
    st.code("[i**2 for i in range(100)]")

```python
[i**2 for i in range(100)]
```

In [19]:
# |exporti

option = st.radio("Choose one option", options=["foo", "bar"], index=1)

RadioButtons(description='Choose one option', index=1, options=('foo', 'bar'), value='bar')

In [20]:
# |exporti

option = st.selectbox("Selectbox: ", options=["Jane", "Bob", "Alice"], index=0)

Dropdown(description='Selectbox: ', options=('Jane', 'Bob', 'Alice'), value='Jane')

In [21]:
# |exporti

options = st.multiselect("Multiselect: ", options=["python", "golang", "julia", "rust"])

SelectMultiple(description='Multiselect: ', options=('python', 'golang', 'julia', 'rust'), value=())

In [22]:
# |exporti

options = st.multiselect(
    "Multiselect with defaults: ",
    options=["nbdev", "streamlit", "jupyter", "fastcore"],
    default=["jupyter", "streamlit"],
)

SelectMultiple(description='Multiselect with defaults: ', index=(2, 1), options=('nbdev', 'streamlit', 'jupyte…

In [23]:
# | exporti
st.subheader("st.text:")
st.text("This is a text")
st.text("This is \n multiline text")
st.code("This is multiline \n code", language=None)

### st.text:

```None
This is a text
```

```None
This is
 multiline text
```

```None
This is multiline
 code
```

In [24]:
from nbdev.export import nb_export

nb_export("99_example.ipynb", lib_path="./", name="example")